[features]
seeds = false
skip-lint = false
[programs.localnet]
audit_verify_sol = "ChUtZ8gRfjWvnN6WXCeqKACKk54Nu1fvLdwF567sjeXs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/przem/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"