[features]
seeds = false
skip-lint = false
[programs.localnet]
audit_verify_sol = "H6n992DsHKFqjaUbCuSZzGZh8k2ymje9eXTuYBJVUDj7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://localhost:8899"
wallet = "/Users/przem/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
