[features]
seeds = false
skip-lint = false
[programs.localnet]
solkeeper = "Cg96DsFYhhd9drE77seUS3Tqg1t8GvEFwt4mACJ1SMvj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://localhost:8899"
wallet = "admin.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
